#!/usr/bin/env python3
"""Generate TypeScript article objects for articles 6-26."""
import json

articles = []

# Article 6: cuantas-sesiones-psicologia-necesito
articles.append({
  "slug": "cuantas-sesiones-psicologia-necesito",
  "categoryCA": "Com funciona la teràpia",
  "categoryES": "Cómo funciona la terapia",
  "titleCA": "Quantes sessions de psicologia necessito?",
  "titleES": "¿Cuántas sesiones de psicología necesito?",
  "excerptCA": "No existeix un nombre fixe de sessions de psicologia. Depèn del motiu, la intensitat i els teus objectius. Rangs orientatius segons el tipus de problema i com es mesura el progrés.",
  "excerptES": "No hay un número fijo de sesiones de psicología. Depende del motivo, la intensidad y tus objetivos. Rangos orientativos según el tipo de problema y cómo se mide el progreso.",
  "datePublished": "2026-06-27",
  "blocksES": [
    {"type": "paragraph", "text": "Es una de las preguntas más frecuentes en la primera sesión, y tiene todo el sentido: uno quiere saber qué compromiso de tiempo y dinero está asumiendo. La respuesta honesta es que un psicólogo responsable no puede darte un número cerrado en la primera visita, pero sí puede darte un horizonte orientativo y explicarte qué factores lo acortan o lo alargan."},
    {"type": "heading", "text": "Qué determina el número de sesiones"},
    {"type": "paragraph", "text": "Tres factores explican la mayoría de las diferencias entre un proceso corto y uno largo."},
    {"type": "paragraph", "text": "El motivo de consulta. Una dificultad puntual (un duelo reciente, una decisión laboral, un episodio de estrés agudo) suele resolverse en menos sesiones que un problema crónico o un patrón que lleva años instalado. Un trastorno de ansiedad generalizada, por ejemplo, requiere más trabajo que una fobia específica."},
    {"type": "paragraph", "text": "La intensidad y el impacto funcional. Si el problema te impide trabajar, dormir o mantener relaciones, el proceso incluye estabilización antes del cambio profundo, y eso alarga el recorrido. Si funciona razonablemente bien y el malestar es puntual, se trabaja más rápido."},
    {"type": "paragraph", "text": "Tus objetivos. No todo el mundo busca lo mismo. Hay quien quiere aliviar un síntoma concreto en pocas semanas; hay quien quiere comprender un patrón que se repite en sus relaciones desde hace años. El primer objetivo se alcanza en menos sesiones; el segundo, no."},
    {"type": "heading", "text": "Rangos orientativos por tipo de problema"},
    {"type": "paragraph", "text": "Con la cautela de que cada caso es distinto, estos son los rangos que solemos manejar en consulta:"},
    {"type": "list", "items": [
      "Acompañamiento puntual (duelo, decisión, estrés agudo): 4-8 sesiones. Trabajo enfocado, con un objetivo claro y cerrado.",
      "Ansiedad o tristeza reactiva de intensidad media: 8-16 sesiones. Tiempo para identificar el patrón, aprender herramientas y consolidar cambios.",
      "Trastornos más persistentes (TDAH, TOC, trastornos de personalidad): de varios meses a un año o más, con fases de trabajo activo y fases de seguimiento más espaciado.",
      "Procesos de autoconocimiento o cambio profundo: abiertos, sin un cierre fechado. Se revisa cada pocas sesiones si sigue teniendo sentido continuar.",
    ]},
    {"type": "paragraph", "text": "Estos números no son promesas. Son una forma de que te hagas a la idea del orden de magnitud antes de empezar. En la primera sesión, el psicólogo puede afinar el horizonte después de evaluar tu caso."},
    {"type": "heading", "text": "Con qué frecuencia se hacen las sesiones"},
    {"type": "paragraph", "text": "Lo habitual es empezar con una sesión semanal. Esa frecuencia permite construir la alianza terapéutica, mantener el hilo del trabajo entre sesiones y corregir antes de que un patrón se reinstale. Cuando el cambio se consolida, se espacia: una sesión cada quince días, luego cada tres semanas, y finalmente sesiones de seguimiento mensual o puntual."},
    {"type": "paragraph", "text": "Espaciar antes de tiempo es uno de los errores más comunes. Cuando uno se siente mejor, la tentación es reducir ritmo, pero si se hace demasiado pronto el síntoma suele volver. Por eso el espaciado lo decide el terapeuta junto con la persona, no como un ahorro automático."},
    {"type": "paragraph", "text": "La duración de cada sesión suele ser de 50-60 minutos. Eso da tiempo a explorar un tema con profundidad sin saturar. Las sesiones más largas no suelen ser mejores; las más cortas muchas veces no alcanzan para trabajar lo que se necesita."},
    {"type": "heading", "text": "Cómo se sabe que la terapia está funcionando"},
    {"type": "paragraph", "text": "El progreso en terapia no siempre es lineal. Hay semanas de avance claro y semanas de estancamiento, y eso no significa que el proceso no funcione. Lo que sí permite saber si va bien es valorar, cada cierto tiempo, tres cosas: si el síntoma que motivó la consulta disminuye, si dispones de más recursos para gestionarlo y si tu funcionamiento cotidiano mejora."},
    {"type": "paragraph", "text": "Un buen profesional revisa el plan de trabajo cada 4-6 sesiones. Si no hay cambios en ese periodo, conviene hablarlo abiertamente: a veces hay que ajustar el enfoque, a veces los objetivos, y a veces derivar a otro perfil. Que la terapia funcione no se mide en sesiones acumuladas, sino en cambios sostenidos en tu vida."},
    {"type": "heading", "text": "Cómo enfocamos la duración en Espai Emocions"},
    {"type": "paragraph", "text": "En nuestro equipo trabajamos con un plan de tratamiento explícito. Tras las primeras sesiones de valoración, el profesional plantea un objetivo concreto, una hipótesis de trabajo y un horizonte orientativo de sesiones. Ese plan se revisa con cada persona de forma periódica, y se ajusta según la evolución."},
    {"type": "paragraph", "text": "No alargamos procesos por sistema ni los cerramos antes de tiempo para aparentar eficacia. Si el cambio se consolida, espaciamos. Si no avanza, lo hablamos y, si conviene, derivamos dentro del equipo a un perfil más específico. La transparencia sobre cuánto va a durar el trabajo forma parte del encuadre terapéutico."},
  ],
  "blocksCA": [
    {"type": "paragraph", "text": "És una de les preguntes més freqüents en la primera sessió, i té tot el sentit: un vol saber quin compromís de temps i diners està assumint. La resposta honesta és que un psicòleg responsable no pot donar-te un nombre tancat en la primera visita, però sí pot donar-te un horitzó orientatiu i explicar-te quins factors l'escurcen o l'allarguen."},
    {"type": "heading", "text": "Què determina el nombre de sessions"},
    {"type": "paragraph", "text": "Tres factors expliquen la majoria de les diferències entre un procés curt i un de llarg."},
    {"type": "paragraph", "text": "El motiu de consulta. Una dificultat puntual (un dol recent, una decisió laboral, un episodi d'estrès agut) sol resoldre's en menys sessions que un problema crònic o un patró que porta anys instal·lat. Un trastorn d'ansietat generalitzada, per exemple, requereix més treball que una fòbia específica."},
    {"type": "paragraph", "text": "La intensitat i l'impacte funcional. Si el problema t'impedeix treballar, dormir o mantenir relacions, el procés inclou estabilització abans del canvi profund, i això allarga el recorregut. Si funciona raonablement bé i el malestar és puntual, es treballa més ràpid."},
    {"type": "paragraph", "text": "Els teus objectius. No tothom busca el mateix. Hi ha qui vol alleujar un símptoma concret en poques setmanes; hi ha qui vol comprendre un patró que es repeteix en les seves relacions des de fa anys. El primer objectiu s'assoleix en menys sessions; el segon, no."},
    {"type": "heading", "text": "Rangs orientatius per tipus de problema"},
    {"type": "paragraph", "text": "Amb la cautela que cada cas és diferent, aquests són els rangs que solen manejar-se en consulta:"},
    {"type": "list", "items": [
      "Acompanyament puntual (dol, decisió, estrès agut): 4-8 sessions. Treball enfocat, amb un objectiu clar i tancat.",
      "Ansietat o tristesa reactiva d'intensitat mitjana: 8-16 sessions. Temps per identificar el patró, aprendre eines i consolidar canvis.",
      "Trastorns més persistents (TDAH, TOC, trastorns de personalitat): de diversos mesos a un any o més, amb fases de treball actiu i fases de seguiment més espaiat.",
      "Processos d'autoconeixement o canvi profund: oberts, sense un tancament datat. Es revisa cada poques sessions si segueix tenint sentit continuar.",
    ]},
    {"type": "paragraph", "text": "Aquests nombres no són promeses. Són una forma que et facis a la idea de l'ordre de magnitud abans de començar. En la primera sessió, el psicòleg pot afinar l'horitzó després d'avaluar el teu cas."},
    {"type": "heading", "text": "Amb quina freqüència es fan les sessions"},
    {"type": "paragraph", "text": "L'habitual és començar amb una sessió setmanal. Aquesta freqüència permet construir l'aliança terapèutica, mantenir el fil del treball entre sessions i corregir abans que un patró es reinstal·li. Quan el canvi es consolida, s'espacia: una sessió cada quinze dies, després cada tres setmanes, i finalment sessions de seguiment mensual o puntual."},
    {"type": "paragraph", "text": "Espaciar abans d'hora és un dels errors més comuns. Quan un se sent millor, la temptació és reduir ritme, però si es fa massa aviat el símptoma sol tornar. Per això l'espaiat el decideix el terapeuta juntament amb la persona, no com un estalvi automàtic."},
    {"type": "paragraph", "text": "La durada de cada sessió sol ser de 50-60 minuts. Això dóna temps a explorar un tema amb profunditat sense saturar. Les sessions més llargues no solen ser millors; les més curtes moltes vegades no assoleixen per treballar el que cal."},
    {"type": "heading", "text": "Com se sap que la teràpia està funcionant"},
    {"type": "paragraph", "text": "El progrés en teràpia no sempre és lineal. Hi ha setmanes d'avanç clar i setmanes d'estancament, i això no significa que el procés no funcioni. El que sí permet saber si va bé és valorar, cada cert temps, tres coses: si el símptoma que va motivar la consulta disminueix, si disposes de més recursos per gestionar-lo i si el teu funcionament cotidià millora."},
    {"type": "paragraph", "text": "Un bon professional revisa el pla de treball cada 4-6 sessions. Si no hi ha canvis en aquest període, convé parlar-ne obertament: a vegades cal ajustar l'enfocament, a vegades els objectius, i a vegades derivar a un altre perfil. Que la teràpia funcioni no es mesura en sessions acumulades, sinó en canvis sostinguts en la teva vida."},
    {"type": "heading", "text": "Com enfoquem la durada a Espai Emocions"},
    {"type": "paragraph", "text": "En el nostre equip treballem amb un pla de tractament explícit. Després de les primeres sessions de valoració, el professional planteja un objectiu concret, una hipòtesi de treball i un horitzó orientatiu de sessions. Aquest pla es revisa amb cada persona de forma periòdica, i s'ajusta segons l'evolució."},
    {"type": "paragraph", "text": "No allarguem processos per sistema ni els tanquem abans d'hora per aparentar eficàcia. Si el canvi es consolida, espaiem. Si no avança, en parlem i, si convé, derivem dins de l'equip a un perfil més específic. La transparència sobre quant durarà el treball forma part de l'encuadre terapèutic."},
  ],
})

# Article 7: diferencias-psicologo-psiquiatra
articles.append({
  "slug": "diferencias-psicologo-psiquiatra",
  "categoryCA": "General",
  "categoryES": "General",
  "titleCA": "Diferències entre psicòleg i psiquiatre: quin necessites?",
  "titleES": "Diferencias entre Psicólogo y Psiquiatra",
  "excerptCA": "Una guia clara per entendre les diferències entre psicòleg i psiquiatre, què estudia cada un, quins tractaments ofereixen, i quan acudir a cada un.",
  "excerptES": "Una guía clara para entender las diferencias entre psicólogo y psiquiatra, qué estudia cada uno, qué tratamientos ofrecen, y cuándo acudir a cada uno.",
  "datePublished": "2026-04-18",
  "blocksES": [
    {"type": "paragraph", "text": "Es una de las preguntas más frecuentes: ¿psicólogo o psiquiatra? La respuesta depende de tu situación. Aquí tienes una guía clara para entender la diferencia y tomar la decisión adecuada."},
    {"type": "heading", "text": "La diferencia fundamental"},
    {"type": "paragraph", "text": "Psiquiatra = médico. Ha estudiado medicina (6 años), hecho el MIR (Médico Interno Residente), y se ha especializado en psiquiatría (4 años más). Puede diagnosticar y recetar medicación."},
    {"type": "paragraph", "text": "Psicólogo = profesional de la psicología. Ha estudiado psicología (4-5 años) y tiene formación especializada en salud mental (máster, PIR en algunos casos). Trabaja con terapia psicológica, no prescribe medicamentos."},
    {"type": "heading", "text": "Comparación detallada"},
    {"type": "paragraph", "text": "Formación base: Psicología (4-5 años + Máster en salud mental) vs Medicina (6 años + MIR en psiquiatría, 4 años). Título: Psicólogo/a General Sanitario o Especialista vs Médico Especialista en Psiquiatría. Enfoque principal: Procesos psicológicos, emociones, comportamientos vs Aspectos biológicos del cerebro, neuroquímica. Tratamiento principal: Terapia psicológica (psicoterapia) vs Medicación y tratamiento biológico. ¿Puede recetar?: No (en España) vs Sí. Diagnóstico: Evaluación psicológica, tests vs Diagnóstico médico y psicopatológico. Frecuencia sesiones: Semanal o quincenal, 50-60 min vs Variable, suele ser menos frecuente. Duración tratamiento: Meses a años según caso vs Según necesidad médica."},
    {"type": "paragraph", "text": "Importante: Ambos profesionales están regulados oficialmente en España y deben estar colegiados para ejercer. Siempre puedes verificar su titulación en el Colegio correspondiente."},
    {"type": "heading", "text": "¿Cuándo acudir al psicólogo?"},
    {"type": "paragraph", "text": "El psicólogo es el profesional adecuado cuando:"},
    {"type": "list", "items": [
      "Ansiedad, estrés, fobias leves-moderadas",
      "Depresión leve-moderada",
      "Problemas relacionales o de pareja",
      "Dificultades de autoestima",
      "Crisis vitales, decisiones importantes",
      "Duelo y pérdidas",
      "Crecimiento personal",
      "Adicciones comportamentales (ludopatía, porno)",
      "Quieres entender patrones emocionales profundos",
    ]},
    {"type": "heading", "text": "¿Cuándo acudir al psiquiatra?"},
    {"type": "paragraph", "text": "El psiquiatra es el profesional indicado cuando:"},
    {"type": "list", "items": [
      "Depresión severa o con riesgo suicida",
      "Trastorno bipolar",
      "Esquizofrenia u otros trastornos psicóticos",
      "Trastornos graves que requieren medicación",
      "Cuando la terapia sola no es suficiente",
      "Necesitas ajuste de medicación",
      "Síntomas físicos importantes (insomnio severo, cambios de peso extremos)",
    ]},
    {"type": "heading", "text": "Cuando ambos profesionales son necesarios"},
    {"type": "paragraph", "text": "Muchas situaciones se benefician de la combinación de ambos enfoques. Casos donde terapia + medicación funciona mejor: Depresión moderada-severa, Trastorno de ansiedad severo, TOC, Trastorno por estrés postraumático, Trastornos de la conducta alimentaria, Adicciones severas."},
    {"type": "paragraph", "text": "En estos casos, el psiquiatra gestiona la medicación y el psicólogo trabaja la parte terapéutica. Es una colaboración muy efectiva que ofrece lo mejor de ambos mundos."},
    {"type": "heading", "text": "¿Puedo empezar por el psicólogo?"},
    {"type": "paragraph", "text": "Para la mayoría de problemas cotidianos, sí. El psicólogo puede evaluar tu situación y determinar si necesitas: Solo terapia psicológica, Terapia + derivación a psiquiatra para valoración farmacológica, o Derivación prioritaria a psiquiatra (casos severos)."},
    {"type": "paragraph", "text": "Muchas personas empiezan con el psicólogo y, si es necesario, este las deriva al psiquiatra. Es un camino habitual y completamente válido."},
    {"type": "heading", "text": "Mitos comunes"},
    {"type": "paragraph", "text": "Mito 1: \"El psiquiatra es para los 'locos'\". Realidad: Los psiquiatras tratan una amplia gama de problemas, desde ansiedad hasta condiciones más severas. No hay que tener un \"diagnóstico grave\" para consultarlos."},
    {"type": "paragraph", "text": "Mito 2: \"El psicólogo no sirve para nada grave\". Realidad: La terapia psicológica es efectiva para muchos problemas, incluso severos. A menudo es la intervención principal, con o sin medicación."},
    {"type": "paragraph", "text": "Mito 3: \"Tengo que elegir uno u otro\". Realidad: Puedes ver ambos simultáneamente. De hecho, es lo ideal en muchos casos — que trabajen en coordinación."},
    {"type": "heading", "text": "En resumen"},
    {"type": "paragraph", "text": "Si tu problema es principalmente emocional, conductual, relacional, y quieres trabajar en profundidad, empieza con un psicólogo. Si hay síntomas físicos importantes, necesidad de medicación, o la situación es severa, el psiquiatra es esencial."},
    {"type": "paragraph", "text": "Y recuerda: no hay \"opción incorrecta\". Lo peor que puede pasar es que te deriven al otro profesional si es necesario. Lo importante es pedir ayuda."},
    {"type": "paragraph", "text": "Si tienes dudas, la primera consulta con un psicólogo te permitirá evaluar tu situación y recibir orientación sobre qué camino seguir."},
  ],
  "blocksCA": [
    {"type": "paragraph", "text": "És una de les preguntes més freqüents: psicòleg o psiquiatre? La resposta depèn de la teva situació. Aquí tens una guia clara per entendre la diferència i prendre la decisió adequada."},
    {"type": "heading", "text": "La diferència fonamental"},
    {"type": "paragraph", "text": "Psiquiatre = metge. Ha estudiat medicina (6 anys), fet el MIR (Metge Intern Resident), i s'ha especialitzat en psiquiatria (4 anys més). Pot diagnosticar i receptar medicació."},
    {"type": "paragraph", "text": "Psicòleg = professional de la psicologia. Ha estudiat psicologia (4-5 anys) i té formació especialitzada en salut mental (màster, PIR en alguns casos). Treballa amb teràpia psicològica, no prescriu medicaments."},
    {"type": "heading", "text": "Comparació detallada"},
    {"type": "paragraph", "text": "Formació base: Psicologia (4-5 anys + Màster en salut mental) vs Medicina (6 anys + MIR en psiquiatria, 4 anys). Títol: Psicòleg/a General Sanitari o Especialista vs Metge Especialista en Psiquiatria. Enfocament principal: Processos psicològics, emocions, comportaments vs Aspectes biològics del cervell, neuroquímica. Tractament principal: Teràpia psicològica (psicoteràpia) vs Medicació i tractament biològic. Pot receptar?: No (a Espanya) vs Sí. Diagnòstic: Avaluació psicològica, tests vs Diagnòstic mèdic i psicopatològic. Freqüència sessions: Setmanal o quinzenal, 50-60 min vs Variable, sol ser menys freqüent. Durada tractament: Mesos a anys segons cas vs Segons necessitat mèdica."},
    {"type": "paragraph", "text": "Important: Ambdós professionals estan regulats oficialment a Espanya i han d'estar col·legiats per exercir. Sempre pots verificar la seva titulació al Col·legi corresponent."},
    {"type": "heading", "text": "Quan acudir al psicòleg?"},
    {"type": "paragraph", "text": "El psicòleg és el professional adequat quan:"},
    {"type": "list", "items": [
      "Ansietat, estrès, fòbies lleus-moderades",
      "Depressió lleu-moderada",
      "Problemes relacionals o de parella",
      "Dificultats d'autoestima",
      "Crises vitals, decisions importants",
      "Dol i pèrdues",
      "Creixement personal",
      "Addiccions comportamentals (ludopatia, porno)",
      "Vols entendre patrons emocionals profunds",
    ]},
    {"type": "heading", "text": "Quan acudir al psiquiatre?"},
    {"type": "paragraph", "text": "El psiquiatre és el professional indicat quan:"},
    {"type": "list", "items": [
      "Depressió severa o amb risc suïcida",
      "Trastorn bipolar",
      "Esquizofrènia o altres trastorns psicòtics",
      "Trastorns greus que requereixen medicació",
      "Quan la teràpia sola no és suficient",
      "Necessites ajust de medicació",
      "Símptomes físics importants (insomni sever, canvis de pes extrems)",
    ]},
    {"type": "heading", "text": "Quan ambdós professionals són necessaris"},
    {"type": "paragraph", "text": "Moltes situacions es beneficien de la combinació d'ambdós enfocaments. Casos on teràpia + medicació funciona millor: Depressió moderada-severa, Trastorn d'ansietat sever, TOC, Trastorn per estrès postraumàtic, Trastorns de la conducta alimentària, Addiccions severes."},
    {"type": "paragraph", "text": "En aquests casos, el psiquiatre gestiona la medicació i el psicòleg treballa la part terapèutica. És una col·laboració molt efectiva que ofereix el millor d'ambdós mons."},
    {"type": "heading", "text": "Puc començar pel psicòleg?"},
    {"type": "paragraph", "text": "Per a la majoria de problemes quotidians, sí. El psicòleg pot avaluar la teva situació i determinar si necessites: Només teràpia psicològica, Teràpia + derivació a psiquiatria per valoració farmacològica, o Derivació prioritària a psiquiatria (casos severs)."},
    {"type": "paragraph", "text": "Moltes persones comencen amb el psicòleg i, si és necessari, aquest les deriva al psiquiatre. És un camí habitual i completament vàlid."},
    {"type": "heading", "text": "Mites comuns"},
    {"type": "paragraph", "text": "Mite 1: \"El psiquiatre és per als 'bojos'\". Realitat: Els psiquiatres tracten una àmplia gamma de problemes, des d'ansietat fins a condicions més severes. No cal tenir un \"diagnòstic greu\" per consultar-los."},
    {"type": "paragraph", "text": "Mite 2: \"El psicòleg no serveix per a res greu\". Realitat: La teràpia psicològica és efectiva per a molts problemes, fins i tot severs. Sovint és la intervenció principal, amb o sense medicació."},
    {"type": "paragraph", "text": "Mite 3: \"He de triar un o l'altre\". Realitat: Pots veure ambdós simultàniament. De fet, és l'ideal en molts casos — que treballin en coordinació."},
    {"type": "heading", "text": "En resum"},
    {"type": "paragraph", "text": "Si el teu problema és principalment emocional, conductual, relacional, i vols treballar en profunditat, comença amb un psicòleg. Si hi ha símptomes físics importants, necessitat de medicació, o la situació és severa, el psiquiatre és essencial."},
    {"type": "paragraph", "text": "I recorda: no hi ha \"opció incorrecta\". El pitjor que pot passar és que et derivin a l'altre professional si és necessari. L'important és demanar ajuda."},
    {"type": "paragraph", "text": "Si tens dubtes, la primera consulta amb un psicòleg et permetrà avaluar la teva situació i rebre orientació sobre quin camí seguir."},
  ],
})

print(f"Generated {len(articles)} articles so far")
print(json.dumps(articles[0]["slug"]))